---
name: Lint Code Base

on: push

jobs:
    super-lint:
        name: Lint Code Base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Check GITHUB_WORKSPACE var
              run: echo "$GITHUB_WORKSPACE"

            - name: Lint Code Base
              uses: github/super-linter@v4
              env:
                  CSS_FILE_NAME: ./.github/linters/.stylelintrc.json
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  JAVASCRIPT_DEFAULT_STYLE: prettier
                  LINTER_RULES_PATH: /
                  MARKDOWN_CONFIG_FILE: ./.github/linters/.markdown-lint.yml
                  NATURAL_LANGUAGE_CONFIG_FILE: ./.github/linters/.textlintrc.json
                  PERL_CONFIG_FILE: ./.github/linters/.perlcriticrc
                  PYTHON_BLACK_CONFIG_FILE: ./.github/linters/.python-black
                  PYTHON_ISORT_CONFIG_FILE: ./.github/linters/.isort.cfg
                  VALIDATE_YAML: false
